server {
  listen 80;
  server_name _;

  # Landing
  root /usr/share/nginx/html/root;
  index index.html;

  location = / {
    try_files /index.html =404;
  }

  # --- SHEF (static) ---
  location /shef/ {
    alias /usr/share/nginx/html/shef/;
    try_files $uri $uri/ /shef/index.html;
  }

  # --- PREMIUM (static) ---
  location /premium/ {
    alias /usr/share/nginx/html/premium/;
    try_files $uri $uri/ /premium/index.html;
  }

  # --- APIs ---
  location /shef-api/ {
    rewrite ^/shef-api/(.*)$ /$1 break;
    proxy_pass http://shef-api:8080;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }

  location /premium-api/ {
    rewrite ^/premium-api/(.*)$ /$1 break;
    proxy_pass http://premium-backend:3000;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }
}
